env:
  global:
    - NYLAS_ACCESS_TOKEN=7740641a9b32bac91c5b3cd60633071887a07eee

matrix:
  include:
    - os: linux
      env: NODE_VERSION=0.10
    - os: linux
      env: NODE_VERSION=0.12
    - os: linux
      env: NODE_VERSION=4
    - os: osx
      env: NODE_VERSION=0.10
    - os: osx
      env: NODE_VERSION=0.12

sudo: false

install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

script: script/cibuild

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
