language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"

matrix:
  include:
    - os: linux
    - os: osx

sudo: false

script: script/cibuild

addons:
  apt:
    packages:
    - libgnome-keyring-dev
